# Change these first
owner: JonnyIslandNetwork # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: JonnyIsland Website
    url: https://jonnyisland.net
  - name: JonnyIslandHosting billing panel
    url: https://jonnyislandhosting.net
  - name: Pterodactyl panel
    url: $PTERO_PANEL_URL
  - name: Pterodactyl Daemon
    url: $PTERO_DAEMON_URL
    expectedStatusCodes:
      - 401
  - name: Railways Creative MC Server
    url: $RAILWAYS_CREATIVE_MC
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jonnyisland.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: JonnyIsland Status page
  introTitle: "Status page for all of our services."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Main website
      href: https://jonnyisland.net
    - title: Hosting Billing pnnel
      href: https://jonnyislandhosting.net


workflowSchedule:
  uptime: "*/15 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
